# Generated by Django 3.2.9 on 2022-09-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentEmail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentPassword',
            field=models.CharField(max_length=100),
        ),
    ]
