# Generated by Django 3.2.9 on 2022-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220902_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(max_length=100),
        ),
    ]
