# Generated by Django 4.1.1 on 2022-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220902_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AP_ID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
