# Generated by Django 4.1.1 on 2022-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_table_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_table',
            name='name',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_table',
            name='password',
            field=models.CharField(max_length=254),
        ),
    ]
