# Generated by Django 3.2.9 on 2022-11-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_table_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_table',
            name='name',
        ),
        migrations.AddField(
            model_name='student_table',
            name='clg_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student_table',
            name='fname',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student_table',
            name='lname',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student_table',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student_table',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student_table',
            name='prn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student_table',
            name='password',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student_table',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
