# Generated by Django 3.2.9 on 2022-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221124_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AP_ID', models.IntegerField(unique=True)),
                ('prn', models.CharField(blank=True, max_length=50)),
                ('fname', models.CharField(blank=True, max_length=254)),
                ('lname', models.CharField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=254)),
                ('clg_email', models.EmailField(blank=True, max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=254)),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
