# Generated by Django 3.2.9 on 2022-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20221120_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='file_csv_student',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='classroom',
            name='file_csv_teacher',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
