# Generated by Django 3.2.9 on 2022-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20220911_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='coures',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='year',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
