# Generated by Django 3.2.9 on 2022-09-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20220912_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentPrn', models.IntegerField(unique=True)),
                ('studentName', models.CharField(max_length=50)),
                ('studentEmail', models.EmailField(max_length=254)),
                ('studentNumber', models.IntegerField(unique=True)),
            ],
        ),
    ]
