# Generated by Django 3.2.9 on 2022-11-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20221120_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_account_file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
