# Generated by Django 3.2.9 on 2022-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_studentaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_account_file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
