# Generated by Django 3.2.9 on 2022-10-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_createaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccounts',
            name='studentNumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
