# Generated by Django 3.2.9 on 2022-10-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_alter_createaccounts_studentnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=50)),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
