# Generated by Django 3.2.9 on 2022-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_adminaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='AP_ID',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
