# Generated by Django 3.2.9 on 2022-10-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_adminaccount_ap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='loginStatus',
            field=models.BooleanField(default=False),
        ),
    ]
