# Generated by Django 3.2.9 on 2022-11-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_adminaccount_loginstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
    ]
