# Generated by Django 3.2.9 on 2022-11-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseId',
            new_name='course_id',
        ),
    ]
