# Generated by Django 3.2.9 on 2022-11-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_rename_courseid_course_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('year_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
