# Generated by Django 4.2.1 on 2023-05-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="master_img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="papp/images")),
                ("accepted", models.BooleanField(default=False)),
                ("rejected", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="master_user",
            name="otp_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="master_user",
            name="user_m_no",
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name="master_user",
            name="user_name",
            field=models.CharField(default="BAZINGA", max_length=25),
        ),
    ]
