# Generated by Django 4.2.1 on 2023-05-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papp", "0002_master_img_master_user_otp_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master_user",
            name="user_m_no",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
