# Generated by Django 4.2.1 on 2023-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papp", "0003_alter_master_user_user_m_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master_user",
            name="user_m_no",
            field=models.CharField(default=0, unique=True),
        ),
    ]
